[package]
name = "helloworld"
description = "An initial introduction to the rltk framework."

version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rltk.workspace = true
